import { Platform } from "react-native";

const tintColorLight = "#6D28D9";
const tintColorDark = "#A78BFA";

export const Colors = {
  light: {
    text: "#1A1A2E",
    textSecondary: "#64748B",
    textTertiary: "#94A3B8",
    buttonText: "#FFFFFF",
    tabIconDefault: "#94A3B8",
    tabIconSelected: tintColorLight,
    link: "#6D28D9",
    primary: "#6D28D9",
    primaryLight: "#8B5CF6",
    primarySoft: "#EDE9FE",
    secondary: "#4F46E5",
    secondaryLight: "#818CF8",
    accent: "#EC4899",
    accentLight: "#F472B6",
    success: "#059669",
    successLight: "#D1FAE5",
    warning: "#D97706",
    warningLight: "#FEF3C7",
    recording: "#DC2626",
    recordingLight: "#FEE2E2",
    error: "#DC2626",
    errorLight: "#FEE2E2",
    info: "#0284C7",
    infoLight: "#E0F2FE",
    border: "#E2E8F0",
    borderLight: "#F1F5F9",
    backgroundRoot: "#F8FAFC",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#F1F5F9",
    backgroundTertiary: "#E2E8F0",
    backgroundElevated: "#FFFFFF",
    cardShadow: "rgba(100, 116, 139, 0.08)",
    gradientStart: "#6D28D9",
    gradientEnd: "#4F46E5",
    gradientAccent: "#EC4899",
    overlay: "rgba(15, 23, 42, 0.5)",
    shimmer: "#F1F5F9",
  },
  dark: {
    text: "#F1F5F9",
    textSecondary: "#CBD5E1",
    textTertiary: "#64748B",
    buttonText: "#FFFFFF",
    tabIconDefault: "#475569",
    tabIconSelected: tintColorDark,
    link: "#A78BFA",
    primary: "#8B5CF6",
    primaryLight: "#A78BFA",
    primarySoft: "#1E1B4B",
    secondary: "#818CF8",
    secondaryLight: "#A5B4FC",
    accent: "#F472B6",
    accentLight: "#FBCFE8",
    success: "#34D399",
    successLight: "#064E3B",
    warning: "#FBBF24",
    warningLight: "#78350F",
    recording: "#F87171",
    recordingLight: "#7F1D1D",
    error: "#F87171",
    errorLight: "#7F1D1D",
    info: "#38BDF8",
    infoLight: "#0C4A6E",
    border: "#1E293B",
    borderLight: "#334155",
    backgroundRoot: "#0F172A",
    backgroundDefault: "#1E293B",
    backgroundSecondary: "#334155",
    backgroundTertiary: "#475569",
    backgroundElevated: "#1E293B",
    cardShadow: "rgba(0, 0, 0, 0.4)",
    gradientStart: "#7C3AED",
    gradientEnd: "#6366F1",
    gradientAccent: "#EC4899",
    overlay: "rgba(0, 0, 0, 0.7)",
    shimmer: "#334155",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 52,
  buttonHeight: 56,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 32,
  "3xl": 40,
  full: 9999,
};

export const Typography = {
  largeTitle: {
    fontSize: 34,
    fontWeight: "700" as const,
    letterSpacing: -0.5,
  },
  title1: {
    fontSize: 28,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  title2: {
    fontSize: 22,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  header: {
    fontSize: 28,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  headline: {
    fontSize: 17,
    fontWeight: "600" as const,
  },
  title: {
    fontSize: 20,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  body: {
    fontSize: 17,
    fontWeight: "400" as const,
  },
  callout: {
    fontSize: 16,
    fontWeight: "400" as const,
  },
  subheadline: {
    fontSize: 15,
    fontWeight: "400" as const,
  },
  caption: {
    fontSize: 12,
    fontWeight: "500" as const,
    letterSpacing: 0.3,
  },
  link: {
    fontSize: 17,
    fontWeight: "400" as const,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
